name: MLOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mlops-ci:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️ Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3️ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc mlflow

      # 4️ Pull DVC data (optional if you have a remote)
      - name: Pull data with DVC
        run: |
          dvc pull || echo "No DVC remote configured"

      # set MLFlow credentials
      - name: Set MLflow credentials
        run: |
          echo "Setting MLflow credentials"
          export MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}
          export MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}

      # 5️ Run full DVC pipeline (repro your 4 stages)
      - name: Run DVC pipeline
        run: |
          export PYTHONPATH=${PYTHONPATH}:$GITHUB_WORKSPACE/src
          dvc repro


      # 6️ Build Docker image (Flask app at root)
      - name: Build Docker image
        run: |
          docker build -t ml-flask-app .

      # 7️ (Optional) Test Flask app runs
      - name: Run Flask app briefly to test
        run: |
         python app.py &
         sleep 5
